# Generated by Django 3.2.5 on 2021-08-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_ssn_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userstore',
            name='account_type',
            field=models.CharField(choices=[('C', 'Cashier'), ('E', 'Executive')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ssn_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('account_type', models.CharField(choices=[('C', 'Current'), ('S', 'Savings')], default='S', max_length=1)),
                ('amount', models.IntegerField()),
                ('amount_credit_debit', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.customer')),
            ],
        ),
    ]
